const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.join(__dirname, '..');
const html = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
const editor = fs.readFileSync(path.join(root, 'js', 'editor.js'), 'utf8');
const css = fs.readFileSync(path.join(root, 'css', 'style.css'), 'utf8');

assert.match(html, /id="gal-preset-manager"/, 'provides the Galgame preset manager modal');
assert.match(html, /role="dialog"[\s\S]*aria-modal="true"[\s\S]*aria-labelledby="gal-preset-title"/, 'manager modal is accessible');
assert.match(html, /id="gal-preset-title"/, 'manager has a visible title');
assert.match(html, /id="gal-preset-close"/, 'manager has a close button');
assert.match(html, /id="gal-preset-manager-body"/, 'manager has a render target');
assert.match(html, /js\/galgame-dialogue\.js\?v=/, 'loads dialogue domain module');
assert.ok(html.indexOf('js/storage.js') < html.indexOf('js/galgame-dialogue.js') && html.indexOf('js/galgame-dialogue.js') < html.indexOf('js/exporter.js'), 'loads dialogue module after storage and before exporter');

assert.match(editor, /DEFAULT_APPEARANCE\s*=\s*\{[^}]*galPanel\s*:\s*null/, 'appearance defaults preserve an optional Galgame panel snapshot');
assert.match(editor, /function openGalPresetManager\s*\(/, 'opens an independent Galgame preset manager');
assert.match(editor, /data-gal-preset-scope="' \+ scope \+ '"/, 'renders scoped preset lists');
for (const scope of ['built-in', 'personal', 'project']) assert.match(editor, new RegExp("items\\('" + scope + "'"), 'renders ' + scope + ' preset scope');
assert.match(editor, /id="gal-slice-' \+ side \+ '"/, 'renders numeric slice input IDs');
for (const side of ['top', 'right', 'bottom', 'left']) assert.match(editor, new RegExp("\['top','right','bottom','left'\]|'" + side + "'"), 'supports ' + side + ' slice input');
assert.match(editor, /function applyGalPresetToProject\s*\(/, 'applies only an explicit draft snapshot to the project');
assert.match(editor, /GalgameDialogue\.normalizeSlices/, 'normalizes slice changes through the domain module');
assert.match(editor, /GalgameDialogue\.parsePreset/, 'imports portable presets through the domain module');
assert.match(editor, /GalgameDialogue\.serializePreset/, 'exports portable presets through the domain module');
assert.match(editor, /Storage\.saveDialoguePreset/, 'saves imported and personal presets');
assert.match(editor, /Storage\.deleteDialoguePreset/, 'deletes personal presets');
assert.match(editor, /addEventListener\('pointermove'/, 'uses Pointer Events while dragging guides');
assert.match(editor, /borderImage/, 'uses the draft panel as a live nine-slice preview');
assert.match(editor, /ap\.galPanel\s*&&\s*ap\.galPanel\.enabled\s*\?\s*' checked'/, 'checkbox reflects the snapshot enabled flag, not merely snapshot existence');
assert.match(editor, /saveAppearance\(\{\s*galPanel:\s*Object\.assign\(\{\},\s*getAppearance\(\)\.galPanel,\s*\{\s*enabled:\s*false\s*\}\)\s*\}\)/, 'disabling retains the project snapshot and records enabled false');
assert.match(editor, /saveAppearance\(\{\s*galPanel:\s*Object\.assign\(\{\},\s*getAppearance\(\)\.galPanel,\s*\{\s*enabled:\s*true\s*\}\)\s*\}\)/, 're-enabling restores the retained snapshot without replacing its image or slices');
assert.match(editor, /\^image\\\/\(png\|jpeg\|webp\)\$\/i\.test\(file\.type/, 'upload accepts only PNG, JPEG, and WebP MIME types');
assert.match(editor, /img\.onload\s*=\s*function\(\).*naturalWidth[\s\S]*img\.onerror\s*=\s*reject/, 'image decoding waits for onload and rejects decode errors');
assert.match(editor, /\(e\.clientY\s*-\s*rect\.top\)\s*\/\s*rect\.height\s*\*\s*draft\.imageHeight/, 'top guide maps rendered Y coordinates to image pixels');
assert.match(editor, /\(e\.clientX\s*-\s*rect\.left\)\s*\/\s*rect\.width\s*\*\s*draft\.imageWidth/, 'left guide maps rendered X coordinates to image pixels');
assert.match(editor, /removeEventListener\('pointermove',\s*move\)[\s\S]*removeEventListener\('pointerup',\s*end\)/, 'drag completion removes pointer move and up listeners');
assert.equal((editor.match(/function escapeHtml\(s\)/g) || []).length, 1, 'uses one attribute-safe HTML escaper instead of a later weak override');
assert.match(editor, /function escapeHtml\(s\)[\s\S]{0,300}['"]['"]\s*:\s*['"]&#39;['"]/, 'escapes apostrophes as well as HTML delimiters');
assert.match(editor, /function isSafeGalImageSrc\s*\(/, 'validates data-image sources before assigning them to image or CSS properties');
assert.match(editor, /function isSafeGalImageSrc[\s\S]{0,300}!\/\[\\r\\n\\f\\\\"\]\//, 'image-source validation rejects control characters and CSS/attribute escape characters');
assert.match(editor, /isSafeGalImageSrc\(draft\.imageSrc\)/, 'does not inject an unchecked draft image into manager markup');
assert.match(editor, /applyGalPanelPreview\(el,\s*draft,\s*['"]rgba\(0,0,0,\.55\)['"],\s*true\)/, 'manager previews selected drafts even before they are applied/enabled');
assert.match(editor, /forceEnabled\s*\|\|\s*panel\.enabled/, 'preview supports an explicit draft-only enabled override');
assert.doesNotMatch(editor, /el\.style\.borderWidth\s*=\s*['"]1px['"]/, 'nine-slice previews never collapse all borders to 1px');
assert.match(editor, /el\.style\.borderWidth\s*=\s*s\.top\s*\+\s*['"]px\s*['"]\s*\+\s*s\.right/, 'preview border widths are derived from normalized slice values');
assert.match(editor, /if \(galPresetDragCleanup\) galPresetDragCleanup\(\);[\s\S]{0,240}const pointerId\s*=\s*event\.pointerId/, 'starting a drag cleans up prior drag state and records the initiator');
assert.match(editor, /const move\s*=\s*function\(e\)\s*\{\s*if \(e\.pointerId\s*!==\s*pointerId\) return;/, 'drag ignores move events from other pointers');
assert.match(editor, /const end\s*=\s*function\(e\)\s*\{\s*if \(e\s*&&\s*e\.pointerId\s*!==\s*pointerId\) return;/, 'drag cleanup remains callable without a PointerEvent when the modal closes');
assert.match(editor, /try\s*\{\s*personal\s*=\s*await window\.Storage\.getAllDialoguePresets\(\);[\s\S]{0,140}catch[\s\S]{0,100}toast/, 'opening handles preset storage failures visibly');
assert.match(editor, /gal-rename-personal[\s\S]{0,1400}catch\s*\(error\)\s*\{\s*toast/, 'rename storage failures are caught and surfaced');
assert.match(editor, /gal-delete-personal[\s\S]{0,1400}catch\s*\(error\)\s*\{\s*toast/, 'delete storage failures are caught and surfaced');
assert.match(editor, /let draftRevision\s*=\s*0/, 'manager tracks a monotonic draft revision');
assert.match(editor, /const revision\s*=\s*\+\+draftRevision/, 'file operations claim a revision before asynchronous work');
assert.match(editor, /revision\s*!==\s*draftRevision\) return;/, 'stale file completions cannot overwrite a newer draft');
assert.match(editor, /gal-upload-image[\s\S]{0,500}const uploadSession\s*=\s*session;[\s\S]{0,900}uploadSession\s*!==\s*galPresetSession/, 'upload completion validates its manager session after close or reopen');
assert.match(editor, /gal-import-preset[\s\S]{0,500}const importSession\s*=\s*session;[\s\S]{0,1400}importSession\s*!==\s*galPresetSession/, 'import callbacks validate their manager session after close or reopen');
assert.match(editor, /reader\.onerror\s*=\s*function\(\)\s*\{\s*if \(importSession\s*===\s*galPresetSession\s*&&\s*revision\s*===\s*draftRevision\)/, 'stale import errors do not toast in a later manager session');
assert.match(editor, /toast\(['"]图片无法读取/, 'failed uploads provide user feedback without altering the draft');
assert.match(editor, /toast\(error\.message\s*\|\|\s*['"]导入失败['"]\)/, 'failed imports provide user feedback');
assert.match(editor, /let galPresetSession\s*=\s*0/, 'manager has a session token for async operation ownership');
assert.match(editor, /const session\s*=\s*\+\+galPresetSession/, 'each manager opening claims a distinct session');
assert.match(editor, /function isCurrentGalPresetOperation\(revision,\s*targetId\)/, 'async preset actions centralize revision and target ownership checks');
assert.match(editor, /const revision\s*=\s*draftRevision;[\s\S]{0,260}const targetId\s*=\s*selected/, 'save captures the current revision and intended target before storage awaits');
assert.match(editor, /await window\.Storage\.saveDialoguePreset\(next\);[\s\S]{0,180}isCurrentGalPresetOperation\(revision,\s*targetId\)/, 'save verifies ownership after storage completion');
assert.match(editor, /const targetId\s*=\s*selected\.id;[\s\S]{0,300}renameDialoguePreset\(targetId,[\s\S]{0,200}isCurrentGalPresetOperation\(revision,\s*targetId\)/, 'rename uses its captured id and ignores stale results');
assert.match(editor, /const targetId\s*=\s*selected\.id;[\s\S]{0,300}deleteDialoguePreset\(targetId\)[\s\S]{0,200}isCurrentGalPresetOperation\(revision,\s*targetId\)/, 'delete uses its captured id and ignores stale results');
assert.match(editor, /function applyGalPresetToProject\(draft\)[\s\S]{0,260}isSafeGalImageSrc\(draft\.imageSrc\)[\s\S]{0,160}toast\(['"]对话框图片无效，未应用['"]\)/, 'apply explicitly rejects unsafe image sources before project mutation');
assert.match(editor, /parsePreset\(reader\.result\)[\s\S]{0,220}!isSafeGalImageSrc\(incoming\.imageSrc\)[\s\S]{0,160}toast\(['"]导入预设图片无效['"]\)/, 'import rejects unsafe preset images before storage writes');

assert.match(css, /#gal-preset-manager[\s\S]*max-width:\s*min\(1040px,\s*94vw\)/, 'manager uses the requested desktop modal width');
assert.match(css, /@media\s*\(max-width:\s*760px\)[\s\S]*gal-preset/, 'manager has a compact responsive layout');

console.log('galgame dialogue editor source contract passed');
